sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 124.222.230.147
    port: 3306
    database: sky_take_out
    username: remote_user
    password: Nzzwd050924.

  alioss:
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    access-key-id: ${OSS_ACCESS_KEY_ID}
    bucket-name: suifengqishi
    endpoint: oss-cn-beijing.aliyuncs.com

  redis:
    host: localhost
    port: 6379
    database: 0